<#
    CMF INTELLIGENT PIPELINE - 05_50-12 Fitou
    Auto-generated by CMF Automator Generator
    
    FEATURES:
    - Auto-Resume: Skips steps if output files already exist.
    - Isolated Sessions: Runs each step in a fresh Gemini session.
    - Error Handling: Stops immediately if a step fails.
#>

$ErrorActionPreference = "Stop"
$projectPath = "d:\Work\The Conscious Movie Factory December\🇫🇷 Conscious Movie Factory\inputs\Coach Adele\05_50-12 Fitou"
$projectId = "05_50-12 Fitou"
$basePath = "d:\Work\The Conscious Movie Factory December"

function Run-Step {
    param (
        [string]$Name,
        [string[]]$CheckFiles,
        [string]$Command
    )

    $allExist = $true
    foreach ($file in $CheckFiles) {
        $fullCheckPath = Join-Path $projectPath $file
        if (-not (Test-Path $fullCheckPath)) {
            $allExist = $false
            break
        }
    }
    
    if ($allExist) {
        Write-Host "✓ [SKIP] ${Name}: All required files exist." -ForegroundColor DarkGray
        return
    }

    Write-Host "Deploying Agent: $Name..." -ForegroundColor Cyan
    
    # Run in headless mode (Fresh Session)
    $prompt = "Project: $projectId`nPath: $projectPath`nExecute: $Command"
    
    gemini --prompt $prompt
    
    if ($LASTEXITCODE -ne 0) {
        Write-Host "🛑 ERROR: $Name failed." -ForegroundColor Red
        exit 1
    }
    
    # Verify primary output again (first file in array)
    $primaryPath = Join-Path $projectPath $CheckFiles[0]
    if (-not (Test-Path $primaryPath)) {
        Write-Host "⚠️ WARNING: Agent finished but $primaryPath was not created." -ForegroundColor Yellow
    } else {
        Write-Host "✓ [DONE] $Name finished." -ForegroundColor Green
    }
}

Write-Host "╔══════════════════════════════════════════════════════════╗" -ForegroundColor Magenta
Write-Host "║    CMF INTELLIGENT PIPELINE: 05_50-12 Fitou     ║" -ForegroundColor Magenta
Write-Host "╚══════════════════════════════════════════════════════════╝" -ForegroundColor Magenta
Write-Host ""

# --- PHASE 1A: SCRIPT ---

Run-Step -Name "Diagnose" `
         -CheckFiles @("strategy_brief.json", "😎 05_50-12 Fitou - The Brand Avatar 😎.md") `
         -Command "/cmf-phase1a-diagnose"

Run-Step -Name "Narrative" `
         -CheckFiles @("05_50-12 Fitou_Quote_Manifest.md", "05_50-12 Fitou_Quote_Manifest_Enriched.md", "05_50-12 Fitou_premise_analysis.json") `
         -Command "/cmf-phase1a-narrative"

Run-Step -Name "Script" `
         -CheckFiles @("final_script.json") `
         -Command "/cmf-phase1a-script"

# --- PHASE 1B: VISUAL ---

Run-Step -Name "Sonic" `
         -CheckFiles @("05_50-12 Fitou_sonic_sommelier_brief.md") `
         -Command "/cmf-phase1b-sonic"

Run-Step -Name "Storyboard" `
         -CheckFiles @("05_50-12 Fitou_STORYBOARD_PRIMAL.md", "05_50-12 Fitou_STORYBOARD_STRUCTURED.md", "05_50-12 Fitou_STORYBOARD_VISUAL_POETRY.md") `
         -Command "/cmf-phase1b-storyboard"

Run-Step -Name "Motion" `
         -CheckFiles @("05_50-12 Fitou_GMG_PROMPTS.md", "05_50-12 Fitou_CAC_PROMPTS.md") `
         -Command "/cmf-phase1b-motion"

Run-Step -Name "E-Roll (Cultural DNA)" `
         -CheckFiles @("05_50-12 Fitou_ERoll_Deep_Research_Report.md", "05_50-12 Fitou_ERoll_Search_Queries.json", "05_50-12 Fitou_EROLL_AUTHORIZED.md") `
         -Command "/cmf-eroll"

Run-Step -Name "Authorize" `
         -CheckFiles @("05_50-12 Fitou_PROMPTS_AUTHORIZED.md") `
         -Command "/cmf-phase1b-authorize"

# --- PHASE 2: IMAGE GENERATION ---

Write-Host "Checking Image Assets..." -ForegroundColor Cyan
$imagesDir = Join-Path $projectPath "generated_images"

# We run the image generator if the folder doesn't exist OR if user forces it.
Write-Host "Running OpenRouter Image Generator..." -ForegroundColor Cyan
python "$basePath/tools/cmf_image_generator.py" --project "$projectId" --type all

Write-Host ""
Write-Host "✨ PIPELINE COMPLETE FOR 05_50-12 Fitou ✨" -ForegroundColor Green
