"""
CMF Automator Generator
Generates a `RUN_PIPELINE.ps1` script inside a project folder.
The generated script is "Self-Healing": it checks for existing files and skips completed steps.
"""

import os
import argparse
from pathlib import Path

TOOLS_PATH = r"d:\Work\The Conscious Movie Factory December\tools"
BASE_PATH = r"d:\Work\The Conscious Movie Factory December"

TEMPLATE = """<#
    CMF INTELLIGENT PIPELINE - {project_id}
    Auto-generated by CMF Automator Generator
    
    FEATURES:
    - Auto-Resume: Skips steps if output files already exist.
    - Isolated Sessions: Runs each step in a fresh Gemini session.
    - Error Handling: Stops immediately if a step fails.
#>

$ErrorActionPreference = "Stop"
$projectPath = "{project_path}"
$projectId = "{project_id}"
$basePath = "{base_path}"

function Run-Step {{
    param (
        [string]$Name,
        [string[]]$CheckFiles,
        [string]$Command
    )

    $allExist = $true
    foreach ($file in $CheckFiles) {{
        $fullCheckPath = Join-Path $projectPath $file
        if (-not (Test-Path $fullCheckPath)) {{
            $allExist = $false
            break
        }}
    }}
    
    if ($allExist) {{
        Write-Host "✓ [SKIP] $Name: All required files exist." -ForegroundColor DarkGray
        return
    }}

    Write-Host "Deploying Agent: $Name..." -ForegroundColor Cyan
    
    # Run in headless mode (Fresh Session)
    $prompt = "Project: $projectId`nPath: $projectPath`nExecute: $Command"
    
    gemini --prompt $prompt
    
    if ($LASTEXITCODE -ne 0) {{
        Write-Host "🛑 ERROR: $Name failed." -ForegroundColor Red
        exit 1
    }}
    
    # Verify primary output again (first file in array)
    $primaryPath = Join-Path $projectPath $CheckFiles[0]
    if (-not (Test-Path $primaryPath)) {{
        Write-Host "⚠️ WARNING: Agent finished but $primaryPath was not created." -ForegroundColor Yellow
    }} else {{
        Write-Host "✓ [DONE] $Name finished." -ForegroundColor Green
    }}
}}

Write-Host "╔══════════════════════════════════════════════════════════╗" -ForegroundColor Magenta
Write-Host "║    CMF INTELLIGENT PIPELINE: {project_id}     ║" -ForegroundColor Magenta
Write-Host "╚══════════════════════════════════════════════════════════╝" -ForegroundColor Magenta
Write-Host ""

# --- PHASE 1A: SCRIPT ---

Run-Step -Name "Diagnose" `
         -CheckFiles @("strategy_brief.json", "😎 {project_id} - The Brand Avatar 😎.md") `
         -Command "/cmf-phase1a-diagnose"

Run-Step -Name "Narrative" `
         -CheckFiles @("{project_id}_Quote_Manifest.md", "{project_id}_Quote_Manifest_Enriched.md", "{project_id}_premise_analysis.json") `
         -Command "/cmf-phase1a-narrative"

Run-Step -Name "Script" `
         -CheckFiles @("final_script.json") `
         -Command "/cmf-phase1a-script"

# --- PHASE 1B: VISUAL ---

Run-Step -Name "Sonic" `
         -CheckFiles @("{project_id}_sonic_sommelier_brief.md") `
         -Command "/cmf-phase1b-sonic"

Run-Step -Name "Storyboard" `
         -CheckFiles @("{project_id}_STORYBOARD_PRIMAL.md", "{project_id}_STORYBOARD_STRUCTURED.md", "{project_id}_STORYBOARD_VISUAL_POETRY.md") `
         -Command "/cmf-phase1b-storyboard"

Run-Step -Name "Motion" `
         -CheckFiles @("{project_id}_GMG_PROMPTS.md", "{project_id}_CAC_PROMPTS.md") `
         -Command "/cmf-phase1b-motion"

Run-Step -Name "E-Roll (Cultural DNA)" `
         -CheckFiles @("{project_id}_ERoll_Deep_Research_Report.md", "{project_id}_ERoll_Search_Queries.json", "{project_id}_EROLL_AUTHORIZED.md") `
         -Command "/cmf-eroll"

Run-Step -Name "Authorize" `
         -CheckFiles @("{project_id}_PROMPTS_AUTHORIZED.md") `
         -Command "/cmf-phase1b-authorize"

# --- PHASE 2: IMAGE GENERATION ---

Write-Host "Checking Image Assets..." -ForegroundColor Cyan
$imagesDir = Join-Path $projectPath "generated_images"

# We run the image generator if the folder doesn't exist OR if user forces it.
Write-Host "Running OpenRouter Image Generator..." -ForegroundColor Cyan
python "$basePath\tools\cmf_image_generator.py" --project "$projectId" --type all

Write-Host ""
Write-Host "✨ PIPELINE COMPLETE FOR {project_id} ✨" -ForegroundColor Green
"""

def generate_script(project_folder_name):
    # Determine paths
    inputs_dir = Path(BASE_PATH) / "🇫🇷 Conscious Movie Factory" / "inputs" / "Coach Adele"
    project_path = inputs_dir / project_folder_name
    
    if not project_path.exists():
        print(f"Error: Project folder not found: {project_path}")
        return

    # Extract Project ID (e.g., "06_50-12 Monia")
    project_id = project_folder_name
    
    # Fill template
    try:
        script_content = TEMPLATE.format(
            project_id=project_id,
            project_path=str(project_path),
            base_path=BASE_PATH
        )
        
        # Write file
        output_file = project_path / "RUN_PIPELINE.ps1"
        output_file.write_text(script_content, encoding="utf-8")
        
        print(f"✓ Created: {output_file}")
    except Exception as e:
        print(f"Error formatting template for {project_id}: {e}")

# --- MAIN ---
if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--project", help="Specific project folder name (e.g., '06_50-12 Monia')")
    parser.add_argument("--all", action="store_true", help="Generate for all projects in Coach Adele folder")
    args = parser.parse_args()

    if args.project:
        generate_script(args.project)
    elif args.all:
        inputs_dir = Path(BASE_PATH) / "🇫🇷 Conscious Movie Factory" / "inputs" / "Coach Adele"
        for folder in inputs_dir.iterdir():
            if folder.is_dir() and "_" in folder.name:
                generate_script(folder.name)
    else:
        print("Usage: python generate_automator.py --project 'NAME' OR --all")
